language: python

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - python -m unittest discover
  - python setup.py sdist bdist_wheel
  - python -m twine upload --repository testpypi dist/*
