language: python

jobs:
  include:
    - stage: test-deploy
      if: branch = master
      install:
        - pip install pipenv
        - pipenv install --dev

      script:
        - python -m unittest discover
        - python setup.py sdist bdist_wheel
        - python -m twine upload --repository testpypi dist/*

    - stage: release-deploy
      if: branch =~ /v.*/
      install:
        - pip install pipenv
        - pipenv install --dev

      script:
        - python -m unittest discover
        - python setup.py sdist bdist_wheel
        - TWINE_PASSWORD="${PRODUCTION_TWINE_PASSWORD}" python -m twine upload dist/*
