from .build_test import KubeDevBuildTests
from .generate_ci_test import KubeDevGenerateCITests
from .generate_deployment_test import KubeDevGenerateDeploymentTests
from .template_test import KubeDevTemplateTests
