apiVersion: apps/v1
kind: Deployment
metadata:
  name: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
  labels:
    kubedev-app: %%KUBEDEV_PROJECT_NAME%% # OVERWRITE
    kubedev-deployment: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
spec:
  replicas: %%KUBEDEV_DEPLOYMENT_REPLICAS%% # OVERWRITE
  selector:
    matchLabels:
      kubedev-app: %%KUBEDEV_PROJECT_NAME%% # OVERWRITE
      kubedev-deployment: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        kubedev-app: %%KUBEDEV_PROJECT_NAME%% # OVERWRITE
        kubedev-deployment: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
    spec:
      securityContext:
        runAsUser: 2001
        runAsGroup: 3001
        fsGroup: 3001
        runAsNonRoot: true
      imagePullSecrets:
      - name: %%KUBEDEV_IMAGEPULLSECRETS%%
