apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %%KUBEDEV.DEPLOYMENT_NAME%% # OVERWRITE
  labels:
    kubedev-app: %%KUBEDEV.PROJECT_NAME%% # OVERWRITE
    kubedev-deployment: %%KUBEDEV.DEPLOYMENT_NAME%% # OVERWRITE
spec:
  replicas: %%KUBEDEV.DEPLOYMENT_REPLICAS%% # OVERWRITE
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        kubedev-app: %%KUBEDEV.PROJECT_NAME%% # OVERWRITE
        kubedev-deployment: %%KUBEDEV.DEPLOYMENT_NAME%% # OVERWRITE
    spec:
      imagePullSecrets:
      - name: %%KUBEDEV.IMAGEPULLSECRETS%%
