apiVersion: v1
kind: Service
metadata:
  name: %%KUBEDEV_SERVICE_NAME%% # OVERWRITE
  labels:
    kubedev-app: %%KUBEDEV_PROJECT_NAME%% # OVERWRITE
    kubedev-deployment: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
spec:
  type: %%KUBEDEV_SERVICE_TYPE%%
  selector:
    kubedev-app: %%KUBEDEV_PROJECT_NAME%% # OVERWRITE
    kubedev-deployment: %%KUBEDEV_DEPLOYMENT_NAME%% # OVERWRITE
